inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

# missing top-level class documentation commentの除外設定
Documentation:
  Enabled: false

# frozen_string_literal: trueが付かないようにする
Style/FrozenStringLiteralComment:
  Enabled: false